/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.text.SimpleDateFormat;
import java.time.LocalTime; // <-- DIBUTUHKAN UNTUK CEK JAM
import java.util.Calendar;
import java.util.Date;
import java.time.LocalTime;
import service.ReservasiService;
import util.UserSession;
import tampilan.home; 

/**
 *
 * @author Acer
 */
public class reservasi extends javax.swing.JFrame {

    private String mejaName;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(reservasi.class.getName());

    /**
     * Creates new form reservasi
     */
    public reservasi() {
        initComponents();
    }

    public void setMejaName(String mejaName) {
        this.mejaName = mejaName;
        this.setTitle("Form Reservasi: Meja " + mejaName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        dateChooserTanggal = new com.toedter.calendar.JDateChooser();
        btnCekTanggal = new javax.swing.JButton();
        comboJamMulai = new javax.swing.JComboBox<>();
        txtJamSelesai = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();

        jTextPane1.setText("BAGI PELANGGAN YANG RESERVASI MEJA REGULER AKAN MEMBAYAR BIAYA RESERVASI RP.10.000 DI AKHIR SAAT PEMBAYARAN");
        jScrollPane2.setViewportView(jTextPane1);

        jTextPane2.setText("BAGI PELANGGAN YANG RESERVASI MEJA REGULER AKAN MEMBAYAR BIAYA RESERVASI RP.10.000 DI AKHIR SAAT PEMBAYARAN");
        jScrollPane1.setViewportView(jTextPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCekTanggal.setBackground(new java.awt.Color(102, 255, 51));
        btnCekTanggal.setText("Reservasi");
        btnCekTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekTanggalActionPerformed(evt);
            }
        });

        comboJamMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", " " }));
        comboJamMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJamMulaiActionPerformed(evt);
            }
        });

        txtJamSelesai.setEditable(false);
        txtJamSelesai.setEnabled(false);
        txtJamSelesai.setText("Jam Selesai");
        txtJamSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamSelesaiActionPerformed(evt);
            }
        });

        label1.setText("BAGI RESERVASI REGULER");

        label2.setText("MEMBAYAR BIAYA RESERVASI");

        label3.setText("SEBESAR RP.10.000");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnCekTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCekTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekTanggalActionPerformed

        // ambil tanggal dari JDateChooser
        java.util.Date selectedDate = dateChooserTanggal.getDate();
        String jamMulaiStr = (String) comboJamMulai.getSelectedItem();

        // Validasi dasar (Tanggal dan Jam Mulai tidak boleh kosong)
        if (selectedDate == null || jamMulaiStr == null || jamMulaiStr.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tanggal dan jam dulu.");
            return;
        }
        Calendar calSelected = Calendar.getInstance();
        calSelected.setTime(selectedDate);
        calSelected.set(Calendar.HOUR_OF_DAY, 0);
        calSelected.set(Calendar.MINUTE, 0);
        calSelected.set(Calendar.SECOND, 0);
        calSelected.set(Calendar.MILLISECOND, 0);

        Calendar calToday = Calendar.getInstance();
        calToday.set(Calendar.HOUR_OF_DAY, 0);
        calToday.set(Calendar.MINUTE, 0);
        calToday.set(Calendar.SECOND, 0);
        calToday.set(Calendar.MILLISECOND, 0);

        if (calSelected.before(calToday)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Reservasi tidak dapat dilakukan untuk tanggal yang sudah berlalu.");
            return;
        }

        String jamMulaiClean = jamMulaiStr.replace('.', ':').trim();
        LocalTime chosenStartTime = LocalTime.parse(jamMulaiClean);

        if (calSelected.equals(calToday)) {
            LocalTime now = LocalTime.now();

            if (chosenStartTime.isBefore(now)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Reservasi jam " + jamMulaiClean + " sudah lewat. Silakan pilih jam lain.");
                return;
            }
        }

        String userEmail = util.UserSession.getInstance().getUserEmail();

        // Format Waktu Akhir untuk DB (HH:MM:SS)
        String finalStartTime = jamMulaiClean + ":00";
        LocalTime jamSelesaiLT = chosenStartTime.plusHours(2);
        String finalEndTime = jamSelesaiLT.toString() + ":00";

        // Format Tanggal untuk Pesan
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String tglStr = sdf.format(selectedDate);

        ReservasiService rs = new ReservasiService();
        String konflikMeja = rs.isMejaAvailable(mejaName, selectedDate, finalStartTime, finalEndTime);

        if (konflikMeja != null) {
            if (konflikMeja.equals("ERROR_DB")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Reservasi Gagal! Terjadi kesalahan.");
            } else if (konflikMeja.equals(mejaName)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Gagal! Meja " + mejaName + " sudah dipesan orang lain pada jam tersebut.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Anda Gagal Reservasi. Anda sudah memiliki reservasi aktif di " + konflikMeja + ".");
            }
            return;
        }

// 4. Penyimpanan ke Database
        boolean success = rs.createReservation(userEmail, mejaName, selectedDate, finalStartTime, finalEndTime);

        if (success) {
            String pesan = "Reservasi berhasil untuk meja " + mejaName + ".\nTanggal: " + tglStr + "\nJam Selesai: " + jamSelesaiLT.toString();
            javax.swing.JOptionPane.showMessageDialog(this, pesan);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Reservasi Gagal! Terjadi kesalahan saat menyimpan data.");
        }

        txtJamSelesai.setText(jamSelesaiLT.toString());
    }//GEN-LAST:event_btnCekTanggalActionPerformed

    private void comboJamMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJamMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJamMulaiActionPerformed

    private void txtJamSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamSelesaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Buat instance baru dari frame home
    home h = new home(); // <-- Pastikan ada titik koma di sini
    
    // 2. Tampilkan frame home
    h.setVisible(true);
    
    // 3. Tutup frame 'vip' saat ini
    this.dispose(); // <-- Gunakan dispose() yang benar        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new reservasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekTanggal;
    private javax.swing.JComboBox<String> comboJamMulai;
    private com.toedter.calendar.JDateChooser dateChooserTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField txtJamSelesai;
    // End of variables declaration//GEN-END:variables

}
