package tampilan;

import service.ReservasiService;
import util.UserSession;
import java.time.LocalTime;
import java.util.Calendar;
import tampilan.home;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * VIP Reservation Page - Halaman reservasi khusus untuk meja VIP
 * Menyediakan layanan reservasi premium dengan fitur khusus
 * Menggunakan ReservasiService untuk proses booking
 * 
 * @author Acer
 * @version 1.1
 */
public class vip extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vip.class.getName());
    private final String mejaName = "VIP";

    /**
     * Creates new form vip
     */
    public vip() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserTanggal = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        dateChooserTanggal1 = new com.toedter.calendar.JDateChooser();
        comboJamMulai = new javax.swing.JComboBox<>();
        btnCekTanggal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboJamMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00-13.00", "15.00-20.00" }));

        btnCekTanggal.setBackground(new java.awt.Color(51, 255, 51));
        btnCekTanggal.setText("Reservasi");
        btnCekTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekTanggalActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label1.setText("BAGI RESERVASI VIP");

        label2.setText("MEMBAYAR BIAYA RESERVASI");

        label3.setText("SEBESAR RP.50.000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(dateChooserTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCekTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCekTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekTanggalActionPerformed

        // ambil tanggal dari JDateChooser
        java.util.Date selectedDate = dateChooserTanggal1.getDate();
        String rentangJam = (String) comboJamMulai.getSelectedItem();

        // Validasi dasar
        if (selectedDate == null || rentangJam == null || rentangJam.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tanggal dan rentang jam dulu.");
            return;
        }
        String[] parts = rentangJam.split("-");
        String startTimeVIP = parts[0].replace('.', ':').trim();
        String endTimeVIP = parts[1].replace('.', ':').trim(); // Ambil end time untuk digunakan di bawah

        LocalTime chosenStartTime = LocalTime.parse(startTimeVIP);

        // B. Pengecekan Tanggal (Calendar Logic)
        Calendar calSelected = Calendar.getInstance();
        calSelected.setTime(selectedDate);
        calSelected.set(Calendar.HOUR_OF_DAY, 0);
        calSelected.set(Calendar.MINUTE, 0);
        calSelected.set(Calendar.SECOND, 0);
        calSelected.set(Calendar.MILLISECOND, 0);

        Calendar calToday = Calendar.getInstance();
        calToday.set(Calendar.HOUR_OF_DAY, 0);
        calToday.set(Calendar.MINUTE, 0);
        calToday.set(Calendar.SECOND, 0);
        calToday.set(Calendar.MILLISECOND, 0);

        if (calSelected.before(calToday)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Reservasi tidak dapat dilakukan untuk tanggal yang sudah berlalu.");
            return;
        }

        // C. Pengecekan Jam (Hanya Jika Tanggal = Hari Ini)
        if (calSelected.equals(calToday)) {
            LocalTime now = LocalTime.now();

            if (chosenStartTime.isBefore(now)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Rentang jam VIP yang dipilih sudah dimulai. Silakan pilih rentang jam lain.");
                return;
            }
        }
        String userEmail = util.UserSession.getInstance().getUserEmail(); // Harus dicek null di awal
        String finalStartTime = startTimeVIP + ":00";
        String finalEndTime = endTimeVIP + ":00";

        if (util.UserSession.getInstance() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sesi tidak ditemukan. Silakan login kembali.");
            return;
        }

        ReservasiService rs = new ReservasiService();
        // Gunakan variabel final yang sudah diformat: finalStartTime, finalEndTime
        String konflikMeja = rs.isMejaAvailable(mejaName, selectedDate, finalStartTime, finalEndTime);

        if (konflikMeja != null) { // Jika ada konflik (String nama meja atau "ERROR_DB")

            if (konflikMeja.equals("ERROR_DB")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Reservasi Gagal! Terjadi kesalahan koneksi database.");
            } else if (konflikMeja.equals(mejaName)) {
                // Meja Lock: Meja yang sama (VIP) sudah dipesan orang lain
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Gagal! Meja " + mejaName + " sudah dipesan orang lain pada jam tersebut.");
            } else {
                // User Lock: User sudah punya reservasi di meja lain
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Anda Gagal Reservasi. Anda sudah memiliki reservasi aktif di Meja " + konflikMeja + ".");
            }
            return; // Batalkan proses
        }

// 4. Penyimpanan ke Database
        boolean success = rs.createReservation(userEmail, mejaName, selectedDate, finalStartTime, finalEndTime);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Reservasi VIP berhasil untuk " + finalStartTime + " sampai " + finalEndTime);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Reservasi VIP Gagal! Terjadi kesalahan saat menyimpan data.");
        }

    }//GEN-LAST:event_btnCekTanggalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // 1. Buat instance baru dari frame home
    home h = new home(); // <-- Pastikan ada titik koma di sini
    
    // 2. Tampilkan frame home
    h.setVisible(true);
    
    // 3. Tutup frame 'vip' saat ini
    this.dispose(); // <-- Gunakan dispose() yang benar
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vip().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekTanggal;
    private javax.swing.JComboBox<String> comboJamMulai;
    private com.toedter.calendar.JDateChooser dateChooserTanggal;
    private com.toedter.calendar.JDateChooser dateChooserTanggal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
